Update activity
Improved return statements, added some error traps

diff --git a/activity b/activity
--- a/activity
+++ b/activity
@@ -1,9 +1,16 @@
 #!/bin/bash
+
+set -o errexit   # exit on error
+set -o nounset   # error on undefined variables
+set -o pipefail  # pipelines fail if any command fails
+
+command -v qdbus6 >/dev/null 2>&1 || { echo "Missing qdbus6"; exit 1; }
+
 script="$(basename "$0")"
 
 about_script(){
-    local version="1.0.0"
-    local updated="2nd April 2026"
+    local version="1.1.0"
+    local updated="4th April 2026"
     local creator="Nora Moyer"
     local copyright="CQI Technologies LLC"
     local social="https://bsky.app/profile/noram25.bsky.social"
@@ -24,6 +31,7 @@ activity_count() {
 activity_exists(){
     if [[ "$1" == "" ]]; then
         command_error "--activity-exists" "No activity ID or name provided"
+        return 1
     else
         if [[ "$(internal_validate_id_format "$1")" == "Valid ID" ]] || [[ "$(internal_validate_name_format "$1")" == "Valid name" ]]; then
             local ids=$(list_ids)
@@ -39,18 +47,19 @@ activity_exists(){
                 local name="$(get_name_by_id "$id")"
                 if [[ "$name" == *"$1"* ]] || [[ "$id" == "$1" ]]; then
                     echo "$active    $id    $name"
-                    return
+                    return 0
                 fi
             done <<< "$ids"
             echo ""
         else
             command_error "--activity-exists" "Invalid ID or name provided"
+            return 1
         fi
     fi
 }
 
 activity_info(){
-    local $id="${1,,}"
+    local id="${1,,}"
     id="$(trim "$id")"
     local validate="$(internal_validate_id_format "$id")"
     if [[ "$validate" == "Valid ID" ]]; then
@@ -61,8 +70,10 @@ activity_info(){
         echo "Icon: $(qdbus6 org.kde.ActivityManager /ActivityManager/Activities ActivityIcon "$id")"
         echo "Started: $(qdbus6 org.kde.ActivityManager /ActivityManager/Activities ActivityStarted "$id")"
         echo "State: $(qdbus6 org.kde.ActivityManager /ActivityManager/Activities ActivityState "$id")"
+        return 0
     else
         command_error "--activity-info" "$validate"
+        return 1
     fi
 }
 
@@ -76,12 +87,13 @@ add_activity(){
             local name="$(get_name_by_id "$id")"
             if [[ "$name" == "$name" ]]; then
                 command_error "--add-activity" "Activity with '$name' already exists"
-                return
+                return 0
             fi
         done <<< "$ids"
         qdbus6 org.kde.ActivityManager /ActivityManager/Activities AddActivity "$name"
     else
         command_error "--add-activity" "$validate"
+        return 1
     fi
 }
 
@@ -199,71 +211,73 @@ detect_flags(){
     ## Usage requests
     if [[ "${param1,,}" == "--help" ]] || [[ "${param1,,}" == "-h" ]]  || [[ "$param1" == "?" ]]; then
         command_error "$command" "--help"
-        return
+        return 0
     fi
 
     ## Action requests
     if [[ "$command" == "--about" ]]; then
         about_script
     elif [[ "$command" == "--activity-exists" ]]; then
-            activity_exists "$param1"
+        activity_exists "$param1"
     elif [[ "$command" == "--activity-info" ]]; then
-            activity_info "$param1"
+        activity_info "$param1"
     elif [[ "$command" == "--add-activity" ]]; then
-            add_activity "$param1"
+        add_activity "$param1"
     elif [[ "$command" == "--current-id" ]]; then
-            current_id
+        current_id
     elif [[ "$command" == "--current-name" ]]; then
-            current_name
+        current_name
     elif [[ "$command" == "--export-activities-list" ]]; then
-            export_activities_list "$param1"
+        export_activities_list "$param1"
     elif [[ "$command" == "--functions" ]]; then
-            functions
+        functions
     elif [[ "$command" == "--get-id-by-index" ]]; then
-            get_id_by_index "$param1"
+        get_id_by_index "$param1"
     elif [[ "$command" == "--get-id-by-name" ]]; then
-            get_id_by_name "$param1"
+        get_id_by_name "$param1"
     elif [[ "$command" == "--get-name-by-id" ]]; then
-            get_name_by_id "$param1"
+        get_name_by_id "$param1"
     elif [[ "$command" == "--get-name-by-index" ]]; then
-            get_name_by_index "$param1"
+        get_name_by_index "$param1"
     elif [[ "$command" == "--list-ids" ]]; then
-            list_ids
+        list_ids
     elif [[ "$command" == "--list-names" ]]; then
-            list_names
+        list_names
     elif [[ "$command" == "--next" ]]; then
-            next
+        next
     elif [[ "$command" == "--previous" ]]; then
-            previous
+        previous
     elif [[ "$command" == "--remove-activity" ]]; then
-            remove_activity "$param1"
+        remove_activity "$param1"
     elif [[ "$command" == "--set-description" ]]; then
-            set_description "$param1" "$param2"
+        set_description "$param1" "$param2"
     elif [[ "$command" == "--set-icon" ]]; then
-            set_icon "$param1" "$param2"
+        set_icon "$param1" "$param2"
     elif [[ "$command" == "--set-name" ]]; then
-            set_name "$param1" "$param2"
+        set_name "$param1" "$param2"
     elif [[ "$command" == "--slideshow" ]]; then
-            slideshow "$param1" "$param2"
+        slideshow "$param1" "$param2"
     elif [[ "$command" == "--show-table" ]]; then
-            show_table
+        show_table
     elif [[ "$command" == "--start-activity" ]]; then
-            start_activity "$param1"
+        start_activity "$param1"
     elif [[ "$command" == "--stop-activity" ]]; then
-            stop_activity "$param1"
+        stop_activity "$param1"
     elif [[ "$command" == "--switch-by-id" ]]; then
-            switch_by_id "$param1"
+        switch_by_id "$param1"
     elif [[ "$command" == "--switch-by-name" ]]; then
-            switch_by_name "$param1"
+        switch_by_name "$param1"
     elif [[ "$command" == "--switch-by-index" ]]; then
-            switch_by_index "$param1"
+        switch_by_index "$param1"
     elif [[ "$command" == "--validate-id-format" ]]; then
-            validate_id_format "$param1"
+        validate_id_format "$param1"
     else
         echo "Function '$command' not found."
         echo "Type 'man $script' for the manual."
         echo "Type '$script --functions' for a list of functions."
+        return 1
     fi
+    return 0
 }
 
 export_activities_list(){
@@ -324,8 +338,10 @@ get_id_by_index(){
             fi
         done < <(list_ids)
         echo ""
+        return 0
     else
         command_error "--get-id-by-index" "$validate"
+        return 1
     fi
 }
 
@@ -343,8 +359,10 @@ get_id_by_name(){
             fi
         done <<< "$ids"
         echo ""
+        return 0
     else
         command_error "--get-id-by-name" "$validate"
+        return 1
     fi
 }
 
@@ -354,8 +372,10 @@ get_name_by_id(){
     local validate="$(internal_validate_id_format "$id")"
     if [[ "$validate" == "Valid ID" ]]; then
         qdbus6 org.kde.ActivityManager /ActivityManager/Activities ActivityName "$id"
+        return 0
     else
         command_error "--get-name-by-id" "$validate"
+        return 1
     fi
 }
 
@@ -365,18 +385,19 @@ get_name_by_index(){
     if [[ "$validate" == "Valid index" ]]; then
         local name=""
         local ids=$(list_ids)
-        count=0
+        local count=0
         while read -r id; do
             count=$((count+1))
             local name="$(get_name_by_id "$id")"
             if [[ "$count" == "$index" ]]; then
                 echo "$name"
-                return
+                return 0
             fi
         done <<< "$ids"
         echo ""
     else
         command_error "--get-name-by-index" "$validate"
+        return 1
     fi
 }
 
@@ -390,12 +411,14 @@ internal_validate_id_format(){
             while read -r iditem; do
                 if [[ "$iditem" == "$id" ]]; then
                     echo "Valid ID"
-                    return
+                    return 0
                 fi
             done <<< "$(list_ids)"
             echo "ID does not exist"
+            return 1
         else
             echo "Invalid ID"
+            return 1
         fi
     fi
 }
@@ -405,15 +428,19 @@ internal_validate_index_format(){
     index="$(trim "$index")"
     if [[ "$index" == "" ]]; then
         echo "Missing index"
+        return 1
     else
-        if [[ "$id" =~ ^[1-9]{1}[0-9]{0,2}$ ]]; then
-            if [[ "$1" -le "$(activity_count)" ]]; then
+        if [[ "$index" =~ ^[1-9]{1}[0-9]{0,2}$ ]]; then
+            if [[ "$index" -le "$(activity_count)" ]]; then
                 echo "Valid index"
+                return 0
             else
                 echo "Index out of range"
+                return 1
             fi
         else
             echo "Invalid index"
+            return 1
         fi
     fi
 }
@@ -423,18 +450,19 @@ internal_validate_name_format(){
     name="$(trim "$name")"
     if [[ -z "$name" ]]; then
         echo "Missing name"
-        return
+        return 1
     fi
     if [[ "$name" =~ ^[[:space:]]+$ ]]; then
         echo "Invalid name (only whitespace)"
-        return
+        return 1
     fi
     if [[ "$name" =~ [[:cntrl:]] ]]; then
         echo "Invalid name (contains control characters)"
-        return
+        return 1
     fi
 
     echo "Valid name"
+    return 0
 }
 
 list_ids(){
@@ -465,6 +493,7 @@ remove_activity(){
     ref="$(trim "$ref")"
     if [[ "$ref" == "" ]]; then
         command_error "--remove-activity" "No activity ID or name provided"
+        return 1
     else
         if [[ "$(internal_validate_id_format "$ref")" == "Valid ID" ]] || [[ "$(internal_validate_name_format "$ref")" == "Valid name" ]]; then
             local ids=$(list_ids)
@@ -480,12 +509,14 @@ remove_activity(){
                 if [[ "$name" == "$ref" ]] || [[ "$id" == "$ref" ]]; then
                     qdbus6 org.kde.ActivityManager /ActivityManager/Activities RemoveActivity "$ref"
                     echo "$active    $id    $name"
-                    return
+                    return 0
                 fi
             done <<< "$ids"
             command_error "--remove-activity" "Activity '$ref' not found"
+            return 1
         else
             command_error "--remove-activity" "Invalid ID or name provided"
+            return 1
         fi
     fi
 }
@@ -496,8 +527,10 @@ set_description(){
     local validate="$(internal_validate_id_format "$id")"
     if [[ "$validate" == "Valid ID" ]]; then
         qdbus6 org.kde.ActivityManager /ActivityManager/Activities SetActivityDescription "$id" "$2"
+        return 0
     else
         command_error "--set-description" "$validate"
+        return 1
     fi
 }
 
@@ -511,12 +544,16 @@ set_icon(){
             qdbus6 org.kde.ActivityManager /ActivityManager/Activities SetActivityIcon "$id" "$path"
             if [[ "$(qdbus6 org.kde.ActivityManager /ActivityManager/Activities ActivityIcon "$id")" != "$path" ]]; then
                 command_error "--set-icon" "Could not set icon: '$path'"
+                return 1
             fi
+            return 0
         else
             command_error "--set-icon" "File not found: '$path'"
+            return 1
         fi
     else
         command_error "--set-icon" "$validate"
+        return 1
     fi
 }
 
@@ -526,14 +563,17 @@ set_name(){
     local validate="$(internal_validate_id_format "$id")"
     if [[ "$validate" == "Valid ID" ]]; then
         local name="$2"
-        validate="$(internal_validate_id_format "$name")"
+        validate="$(internal_validate_name_format "$name")"
         if [[ "$validate" == "Valid name" ]]; then
             qdbus6 org.kde.ActivityManager /ActivityManager/Activities SetActivityName "$id" "$name"
+            return 0
         else
             command_error "--set-name" "$validate"
+            return 1
         fi
     else
         command_error "--set-name" "$validate"
+        return 1
     fi
 }
 
@@ -550,6 +590,7 @@ show_table(){
         fi
         echo "$active    $id    $(get_name_by_id "$id")"
     done <<< "$ids"
+    return 0
 }
 
 slideshow(){
@@ -565,6 +606,7 @@ slideshow(){
         done        
     done
     switch_by_id "$current"
+    return 0
 }
 
 start_activity(){
@@ -573,8 +615,10 @@ start_activity(){
     local validate="$(internal_validate_id_format "$id")"
     if [[ "$validate" == "Valid ID" ]]; then
         qdbus6 org.kde.ActivityManager /ActivityManager/Activities StartActivity  "$id"
+        return 0
     else
         command_error "--start-activity" "$validate"
+        return 1
     fi
 }
 
@@ -584,8 +628,10 @@ stop_activity(){
     local validate="$(internal_validate_id_format "$id")"
     if [[ "$validate" == "Valid ID" ]]; then
         qdbus6 org.kde.ActivityManager /ActivityManager/Activities StopActivity  "$id"
+        return 0
     else
         command_error "--stop-activity" "$validate"
+        return 1
     fi
 }
 
@@ -594,6 +640,7 @@ switch_by_id(){
     id="$(trim "$id")"
     if [[ "$id" == "" ]]; then
         command_error "--switch-by-id" "No ID provided"
+        return 1
     else
         local validate="$(validate_id_format "$1")"
         if [[ "$validate" == "Valid ID" ]]; then
@@ -603,26 +650,40 @@ switch_by_id(){
 
             if [[ "$prev_id" != "$1" && "$prev_id" == "$(current_id)" ]]; then
                 command_error "--switch-by-id" "'$1' not found or switch failed"
+                return 1
             fi
+            return 0
         else
             command_error "--switch-by-id" "$validate"
+            return 1
         fi
     fi
 }
 
 switch_by_index(){
     local index="$(trim "$1")"
-    local validate="$(internal_validate_index_format "$index")"
-    if [[ "$validate" != "Valid index" ]]; then
-        command_error "--switch-by-index" "$validate"
+    if [[ "$index" == "" ]]; then
+        command_error "--switch-by-index" "No index provided"
+        return1
     else
-        local prev_id="$(current_id)"
-        local id="$(get_id_by_index "$index")"
-
-        switch_by_id "$id"
-
-        if [[ "$prev_id" != "$id" && "$prev_id" == "$(current_id)" ]]; then
-            command_error "--switch-by-index" "'$index' not found or switch failed"
+        local target_id="$(get_id_by_index "$index")"
+        if [[ "$target_id" == "" ]]; then
+            command_error "--switch-by-index" "'$index' not found"
+            return 1
+        fi
+        local curr_id="$(current_id)"
+        if [[ "$target_id" == "$curr_id" ]]; then
+            command_error "--switch-by-name" "'$name' already selected"
+            return 1
+        else
+            switch_by_id "$target_id"
+            if [[ "$target_id" != "$(current_id)" ]]; then
+                command_error "--switch-by-index" "Switch failed: ID='$target_id', name='$index'"
+                return 1
+            else
+                echo "Switch successful: From '$curr_id' to '$target_id'"
+                return 0
+            fi
         fi
     fi
 }
@@ -631,12 +692,26 @@ switch_by_name(){
     local name="$(trim "$1")"
     if [[ "$name" == "" ]]; then
         command_error "--switch-by-name" "No name provided"
+        return1
     else
-        local tmp_curr="$(current_id)"
-        local id="$(get_id_by_name $1)"
-        switch_by_id "$id"
-        if [[ "$tmp_curr" != "$name" ]] && [[ "$tmp" == "$(current_id)" ]]; then
-            command_error "--switch-by-name" "'$name' not found or switch failed"
+        local target_id="$(get_id_by_name "$name")"
+        if [[ "$target_id" == "" ]]; then
+            command_error "--switch-by-name" "'$name' not found"
+            return 1
+        fi
+        local curr_id="$(current_id)"
+        if [[ "$target_id" == "$curr_id" ]]; then
+            command_error "--switch-by-name" "'$name' already selected"
+            return 1
+        else
+            switch_by_id "$target_id"
+            if [[ "$target_id" != "$(current_id)" ]]; then
+                command_error "--switch-by-name" "Switch failed: ID='$target_id', name='$name'"
+                return 1
+            else
+                echo "Switch successful: From '$curr_id' to '$target_id'"
+                return 0
+            fi
         fi
     fi
 }
@@ -653,11 +728,14 @@ validate_id_format(){
     id="$(trim "$id")"
     if [[ "$id" == "" ]]; then
         command_error "--validate-id-format" "Missing ID"
+        return 1
     else
         if [[ "$id" =~ ^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$ ]]; then
             echo "Valid ID"
+            return 0
         else
             echo "Invalid ID"
+            return 1
         fi
     fi
 }
